[project]
name = "agno-first-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno==2.0",
    "groq>=1.1.2",
    "python-dotenv>=1.2.2",
    "tavily>=1.1.0",
    "tavily-python>=0.7.23",
    "yfinance>=1.2.0",
]
